# Generated by Django 5.1.5 on 2025-01-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_electronicproduct_picture_musicproduct_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicproduct',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='musicproduct',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
